### ISSUE TITLE
Mesaure Text return 0 height

### ISSUE THREAD

**Issue by jsanchezs** [expo/react-native-read-more-text#1]
Hi! First of all, thank you for this implementation! I have try to use it but I have a problem:

When the component ReadMore is calling componentDidMount(), it is trying to get the measures of the text before the restriction of number of lines and after that restriction. In order to do that, it calls `measureHeightAsync`, where is returning the height as a Promise:

```
function measureHeightAsync(component) {
  return new Promise(resolve => {
    component.measure((x, y, w, h) => {
      resolve(h);
    });
  });
}
```

I dont know why, but the first call is always returning me 0 as height.

I'm using an old version of react native, 0.24.1

Thank you!

Jesús

**Comment by eriveltonelias** [comment]
closing since this is not an issue anymore on the latest version.
