### ISSUE TITLE
'Try it on Expo' broken

### ISSUE THREAD

**Issue by nating** [expo/react-native-read-more-text#10]
The [page](https://expo.io/@community/read-more-example) for trying the example on Expo is broken. Scanning the QR Code or entering the url on Expo results in 'No experience found at exp://exp.host/@community/read-more-example.'

<kbd><img width='300' src='https://user-images.githubusercontent.com/16880181/28869409-85cbe260-7774-11e7-99a9-88cfcf7c6a2e.PNG'/></kbd>

**Comment by brentvatne** [comment]
fixed, thanks. now at https://expo.io/@notbrent/read-more-text-example
