### ISSUE TITLE
Text align property does not work in android

### ISSUE THREAD

**Issue by rupalpatel0008** [expo/react-native-read-more-text#21]
Issue: textAlign='center' or 'right' has no effect in android.
react-native version: 0.56.0
![readmore](https://user-images.githubusercontent.com/17310222/44844634-134a9a80-ac69-11e8-8812-86bdba291f51.png)

**Comment by simonefarenza** [comment]
Did you find a solution for that?

**Comment by eriveltonelias** [comment]
Hi @rupalpatel0008 and @simonefarenza 

on 1.1.2 you can add the `textStyle` prop
