### ISSUE TITLE
Display state calls

### ISSUE THREAD

**Issue by mozamonkey** [expo/react-native-read-more-text#22]
I call :
{this.state.Text}
through an API call, but the More button never appear. Does this library work with state calls?

**Comment by mskuser1** [comment]
I had this same error, i solved it by only displaying text when it's ready to be displayed like so:

`if (this.state.isReady){
//display text here
}else{<View></View>}`

The initial value of isReady is false, only becomes true when you have your text ready.

**Comment by eriveltonelias** [comment]
I don't think this is an issue anymore on the latest version of this library, but let me know if you still need help.
