### ISSUE TITLE
Document API of ReadMore component

### ISSUE THREAD

**Issue by solkaz** [expo/react-native-read-more-text#24]
While the usage section does tell you how to use the `ReadMore` component in your app, I would appreciate documentation for it so that:
- It's easier to start using, and clarifies which props are required
  - One example I learned was not supplying a `onReady` callback means that there is a frame where the text is fully visible before the component has measured the text height and covers it
- Helps with creating/maintaining TypeScript definitions

**Comment by eriveltonelias** [comment]
thanks for your report @solkaz! 
I updated our docs to show all props and about TS I'm planning to work on that on the next release.
