### ISSUE TITLE
".measure" returns an undefined height on Android

### ISSUE THREAD

**Issue by MaxInMoon** [expo/react-native-read-more-text#27]
Hi!

I used your awesome component on iOS, and it works, but on Android `component.measure` returns an undefined height in the callback, so it doesn't display the "read more" label.

Replacing `component.measure` by `component.measureInWindow` ([this line](https://github.com/expo/react-native-read-more-text/blob/master/index.js#L102)) did the trick on Android, but will always render the "read more" label on iOS, even if the text is very short.

Any ideas on this?

**Comment by MaxInMoon** [comment]
I handle the thing like so:

```javascript
function measureHeightAsync(component) {
  return new Promise(resolve => {
    if (Platform.OS === 'android') {
      component.measureInWindow((x, y, w, h) => {
        resolve(h);
      });
    }
    else {
      component.measure((x, y, w, h) => {
        resolve(h);
      });
    }
  });
}
```

**Comment by smalljun** [comment]
I have observed that the height of the ios return is floating point, you can use Math.floor to fix the problem that iOS always shows.

**Comment by sasurau4** [comment]
The below comment is works for me.
https://github.com/facebook/react-native/issues/12966#issuecomment-294103409

Hoping this comment will help.

**Comment by eriveltonelias** [comment]
Can you test on the latest version, please?

**Comment by eriveltonelias** [comment]
I'll close the issue for now, but you ping me and I'll reopen to investigate. Thanks for understanding.
