### ISSUE TITLE
Displaying read more even the text is 1 line

### ISSUE THREAD

**Issue by ravalikarumuri** [expo/react-native-read-more-text#28]
I have a chatting screen, sometimes the message with 1 line is also displaying read more text. I have given the condition to display only when the text length is more than 15 lines.

**Comment by LulinhaReparador** [comment]
i changed at the line 31 of index.js this:
old 
`    if (fullHeight > limitedHeight) `
new
`    if (fullHeight - 5 > limitedHeight) `

it works to text with 1 line displaying read more.

**Comment by eriveltonelias** [comment]
Can you provide a runnable repro on https://snack.expo.io ?

**Comment by eriveltonelias** [comment]
I'll close the issue for now, but you can add the repro to the original post and then ping me and I'll reopen to investigate. Thanks for understanding.
