### ISSUE TITLE
v1.0.1 published after 1.1.0?

### ISSUE THREAD

**Issue by draperunner** [expo/react-native-read-more-text#30]
Hi!

`npm outdated` says that there's a new version of react-native-read-more-text out: v1.0.1. But I already have v1.1.0 installed! Did you mean to publish 1.1.1 instead of 1.0.1? :)

<img width="502" alt="image" src="https://user-images.githubusercontent.com/4339443/73491262-813f4800-43ae-11ea-818e-3a39001a7094.png">

**Comment by eriveltonelias** [comment]
thanks @draperunner 
fixed.
