### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): Cannot read property 'measure' of null TypeError: Cannot read property 'measure' of null

### ISSUE THREAD

**Issue by remch1990** [expo/react-native-read-more-text#4]
react-native 0.40 
Os Android

**Comment by rigobcastro** [comment]
@remch1990 Any solution for that? Thanks

**Comment by gameboyVito** [comment]
I am facing the same issue on iOS when I used react-native 0.44. I used the module inside a FlatList, and the renderItem extended to a PureComponent. However, if I use Component, there is no more error shown up, but the performance of FlatList was awful because it's `itemView` should be implemented inside a `PureComponent` just like official doc said. Any solution to support `PureConponent` or `FlatList` in react-native 0.44?

**Comment by tomasfrancisco** [comment]
Getting the same error within a FlatList on iOS.
React Native 0.44.2

**Comment by ronak301** [comment]
+1

**Comment by oliviachang29** [comment]
Same here.

**Comment by jaychsu** [comment]
same issue here

**Comment by gokulkulkarni1987** [comment]
Any fix for this? facing the same issue

**Comment by haciSeydaoglu** [comment]
+1, RN 0.48

**Comment by haciSeydaoglu** [comment]
I used  [react-native-view-more-text](https://github.com/nlt2390/react-native-view-more-text ) and did not have a problem. (RN 0.48)

**Comment by phamhoang2812** [comment]
this issue will appear if you set null value for content (<ReadMore ...> <Text>{null}</Text></ReadMore>)

**Comment by stsiushkevich** [comment]
I have found working approach: to change componentDidMount:

```javascript
  async componentDidMount () {
    if (this._text) {
      await nextFrameAsync()

      if (this._text) {
        const fullHeight = await measureHeightAsync(this._text)
        this.setState({measured: true})
        await nextFrameAsync()

        if (this._text) {
          const limitedHeight = await measureHeightAsync(this._text)
          if (fullHeight > limitedHeight) {
            this.setState({shouldShowReadMore: true}, () => {
              this.props.onReady && this.props.onReady()
            })
          }
        }
      }
    }
  }
```

**Comment by dsah** [comment]
having same issue.

**Comment by rizalibnu** [comment]
Having same issue here

**Comment by Moggieggwp** [comment]
Is this already released?

**Comment by eriveltonelias** [comment]
I don't think this is an issue anymore on the latest version of this library. 
If someone faces this issue, please post a new issue describing the problem.
