### ISSUE TITLE
renderTruncatedFooter And renderRevealedFooter Doesn't work!

### ISSUE THREAD

**Issue by Nygma297** [expo/react-native-read-more-text#6]
```
                                    <ReadMore
                                        numberOfLines={3}
                                        renderTruncatedFooter={this._renderTruncatedFooter}
                                        renderRevealedFooter={this._renderRevealedFooter}
                                        onReady={this._handleTextReady}>
                                        <Text >{data.description}</Text>
                                    </ReadMore>

```

used it like this and then 

```
_renderTruncatedFooter = (handlePress) => {
    return (
        <Text style={{ color: 'blue', marginTop: 5, textAlign: 'right' }} onPress={handlePress}>
            Read more
      </Text>
    );
}

_renderRevealedFooter = (handlePress) => {
    return (
        <Text style={{ color: 'blue', marginTop: 5, textAlign: 'right' }} onPress={handlePress}>
            Show less
      </Text>
    );
}
```
But it isn't working

Please Help!

**Comment by voeurnchy** [comment]
the same problem

**Comment by Nygma297** [comment]
Fixed

**Comment by voeurnchy** [comment]
Can you help me?

**Comment by Nygma297** [comment]
```export default class Gallery extends Component {

	constructor(props) {
		super(props);
		this._renderTruncatedFooter = this._renderTruncatedFooter.bind(this);
		this._renderRevealedFooter = this._renderRevealedFooter.bind(this);
	}

	_renderTruncatedFooter = (handlePress) => {
		return (
			<Text style={{ color: 'blue', marginTop: 5, textAlign: 'right' }} onPress={handlePress}>
				Read more
      </Text>
		);
	}

	_renderRevealedFooter = (handlePress) => {
		return (
			<Text style={{ color: 'blue', marginTop: 5, textAlign: 'right' }} onPress={handlePress}>
				Show less
      </Text>
		);
	}
        render(){
            return(
                       ...
            )
```

**Comment by voeurnchy** [comment]
export default class NotificationContent extends Component{
    
    constructor(props) {
        super(props);
        this._renderTruncatedFooter = this._renderTruncatedFooter.bind(this);
        this._renderRevealedFooter = this._renderRevealedFooter.bind(this);
    }

    _renderTruncatedFooter = (handlePress) => {
        return (
          <RegularText style={{color: Colors.tintColor, marginTop: 5}} onPress={handlePress}>
            Read more
          </RegularText>
        );
      }

    _renderRevealedFooter = (handlePress) => {
        return (
          <RegularText style={{color: Colors.tintColor, marginTop: 5}} onPress={handlePress}>
            Show less
          </RegularText>
        );
      }
    render(){
        return (
                    <View style={{flex: 1}}>
                        <ReadMore
                            numberOfLines={1}
                            renderTruncatedFooter={this._renderTruncatedFooter}
                            renderRevealedFooter={this._renderRevealedFooter}
                            onReady={this._handleTextReady}>
                            <Text style={{color: '#787878'}}>...</Text>
                        </ReadMore>                    
                    </View>
        );     
  }
}

**Comment by Nygma297** [comment]
Remove `RegularText` and add `Text`

**Comment by voeurnchy** [comment]
@Nygma297 Thanks you.

**Comment by Prashant0911** [comment]
what is <ReadMore> here? I am new to react native can you please help.
