### ISSUE TITLE
Use WebView.

### ISSUE THREAD

**Issue by ycpatel813** [expo/react-native-read-more-text#7]
Hello
I found this is a very useful read more functionality you have developed but it only work for Text. Is it possible to use with WebView?

Thank you.

**Comment by jordanmkoncz** [comment]
@ycpatel813 you should probably clarify what you mean here. This library is just taking some normal Text content and then truncating it to a certain number of lines or showing all of it, and I'm not sure how this functionality could apply to a WebView. A WebView is either shown in full (displaying some web page), or not shown at all, right? So I'm not sure how you could use this library's technique in the context of a WebView.

**Comment by eriveltonelias** [comment]
thanks for explain @jordanmkoncz
