### ISSUE TITLE
Curious on the example effect

### ISSUE THREAD

**Issue by smallcar88** [expo/react-native-read-more-text#9]
Hi there,

Thanks for implementing such a useful plugin! I am very curious of the effect on your example GIF showing that the AppBar on top will change the content into a different text when scrolling down. May I ask how can you achieve that on React (Native)?

![](https://raw.githubusercontent.com/expo/react-native-read-more-text/master/example.gif)

Thank you!

**Comment by rigobcastro** [comment]
I have the same curious!

**Comment by shukerullah** [comment]
I have the same curious too!

**Comment by jordanmkoncz** [comment]
The example GIF is showing the use of `react-native-read-more-text` in an open source React Native app called Growler Prowler. The repo can be found at https://github.com/brentvatne/growler-prowler and you can check out the app on your device at https://getexponent.com/@community/growler-prowler.

**Comment by brentvatne** [comment]
:+1:
